# Generated by Django 4.0.5 on 2022-07-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('families', models.FileField(upload_to='file_group_id_f/')),
                ('chromosomes', models.FileField(upload_to='file_group_id_c/')),
                ('colors', models.FileField(upload_to='file_group_id_cl/')),
            ],
        ),
    ]
