# Generated by Django 4.0.5 on 2022-07-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='session_id',
            field=models.CharField(default='ee83c5e994d245249e134bb2e721c0ed', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='information',
            name='chromosomes',
            field=models.FileField(upload_to='session_ee83c5e994d245249e134bb2e721c0ed/chromosomes'),
        ),
        migrations.AlterField(
            model_name='information',
            name='colors',
            field=models.FileField(blank=True, null=True, upload_to='session_ee83c5e994d245249e134bb2e721c0ed/colors'),
        ),
        migrations.AlterField(
            model_name='information',
            name='families',
            field=models.FileField(upload_to='session_ee83c5e994d245249e134bb2e721c0ed/families'),
        ),
    ]
