# Generated by Django 4.0.5 on 2022-07-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0002_information_session_id_alter_information_chromosomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='chromosomes',
            field=models.FileField(upload_to='session_55973ebb294641b58247270d893940f5/chromosomes'),
        ),
        migrations.AlterField(
            model_name='information',
            name='colors',
            field=models.FileField(blank=True, null=True, upload_to='session_55973ebb294641b58247270d893940f5/colors'),
        ),
        migrations.AlterField(
            model_name='information',
            name='families',
            field=models.FileField(upload_to='session_55973ebb294641b58247270d893940f5/families'),
        ),
        migrations.AlterField(
            model_name='information',
            name='session_id',
            field=models.CharField(default='55973ebb294641b58247270d893940f5', editable=False, max_length=255),
        ),
    ]
