# Generated by Django 4.0.5 on 2022-07-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0003_alter_information_chromosomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='chromosomes',
            field=models.FileField(upload_to='session_eaab6ee274f940119170419c7e52f903/chromosomes'),
        ),
        migrations.AlterField(
            model_name='information',
            name='colors',
            field=models.FileField(blank=True, null=True, upload_to='session_eaab6ee274f940119170419c7e52f903/colors'),
        ),
        migrations.AlterField(
            model_name='information',
            name='families',
            field=models.FileField(upload_to='session_eaab6ee274f940119170419c7e52f903/families'),
        ),
        migrations.AlterField(
            model_name='information',
            name='session_id',
            field=models.CharField(default='eaab6ee274f940119170419c7e52f903', editable=False, max_length=255),
        ),
    ]
