# Generated by Django 4.0.5 on 2022-07-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Testapp', '0004_alter_information_chromosomes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='information',
            name='chromosomes',
            field=models.FileField(upload_to='session_fc30e132f2e64a7dae47ff11ec879055/chromosomes'),
        ),
        migrations.AlterField(
            model_name='information',
            name='colors',
            field=models.FileField(blank=True, null=True, upload_to='session_fc30e132f2e64a7dae47ff11ec879055/colors'),
        ),
        migrations.AlterField(
            model_name='information',
            name='families',
            field=models.FileField(upload_to='session_fc30e132f2e64a7dae47ff11ec879055/families'),
        ),
    ]
